language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
  - docker build -t docker02171628/test-docker-vue:latest .
  - docker push docker02171628/test-docker-vue:latest
  